# Generated by Django 5.1.4 on 2025-03-31 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutcontent_contactinfo_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
